server:
  port: 10101


#eureka Configuration
eureka:
  client:
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:10001/eureka

spring:
  application:
    name: SERVICE-DEMO-eureka